### ISSUE TITLE
不要用0表示女性，换其他数

### ISSUE THREAD

**Issue by zhaohy6** [Amayadream/WebChat#19]
https://github.com/Amayadream/WebChat/blob/eed32c6517af7ccf3747d55c6c752b4b8d3c1eda/src/main/webapp/WEB-INF/view/information.jsp#L40

**Comment by zhaohy6** [comment]
重复，提过了

**Comment by xpressdo** [comment]
发错地址了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhaohy6"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月30日(星期六) 中午1:58
收件人:&nbsp;"Amayadream/WebChat"<WebChat@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Amayadream/WebChat] 不要用0表示女性，换其他数 (#19)




Closed #19.
