### ISSUE TITLE
你好,关于你的wechat项目有点疑惑

### ISSUE THREAD

**Issue by Draven1122** [Amayadream/WebChat#2]
在
`   this.userid=(String) httpSession.getAttribute("userid");    //获取当前用户`
这段代码中,userid这个值是在哪里set进去的?

**Comment by amayadream** [comment]
LoginController-line54

session.setAttribute("userid", userid);
session.setAttribute("login_status", true);

**Comment by Amayadream** [comment]
LoginController-line54

session.setAttribute("userid", userid);
session.setAttribute("login_status", true);

**Comment by Draven1122** [comment]
谢谢
