### ISSUE TITLE
HTTP Status 404 -

### ISSUE THREAD

**Issue by EEIT92Team06** [Amayadream/WebChat#3]
嗨您好

我把下載的檔案 "import->General->Projects from forder or Archive" 成功import後

選JSP->RUN 一直顯示404  請問我哪裡出錯了

**Comment by amayadream** [comment]
你应该学习一下如何部署一个JavaWeb项目
首先这是一个Maven构建的项目, 你需要先安装maven
其次需要下载一个tomcat, 将项目编译后放在tomcat中运行
在此之前你需要导入sql文件并确定一下config.properties中的数据库配置.
上面说的这些过程可以通过Eclipse/IntelliJ IDEA来做, 这样比较简便
