### ISSUE TITLE
报两个问题

### ISSUE THREAD

**Issue by AnotherW** [Amayadream/WebChat#6]
1.个人信息和个人设置中头像的图片链接被拦截。
2.系统日志分页有问题，原因是在logserviceimpl的selectLogByUserid方法中调用的selectLogByUserid参数有问题，第二和第三个参数应该分别是 查询截止位置 和 查询行数 。

**Comment by AnotherW** [comment]
ps，还有设置->系统设置  链接是错误的

**Comment by zhang512322977** [comment]
请问这个可不可以实现短语音消息，和语音通话功能

**Comment by amayadream** [comment]
@AnotherW 这个版本很早之前写的, 代码写的挺乱的, 继续修修补补没什么太大意义, 有时间我会开个branch重写一遍, 加上一些新功能

**Comment by daren990** [comment]
这个tomcat用什么版本，7和8都用过了，一直报404错误，websocket始终连不上；

**Comment by amayadream** [comment]
@daren990 7和8都是可以的, 我建议你先检查一下程序是否构建/部署好了.
