### ISSUE TITLE
如何才能将聊天数据保存到数据库呢？

### ISSUE THREAD

**Issue by xifumengmengda** [Amayadream/WebChat#8]
如图，第一个调用的IMessageService接口断点都不进去，是我写的不对吗？请问是为什么呢？
![1](https://user-images.githubusercontent.com/16473366/31890035-65e00192-b834-11e7-84c2-c638bd3d7673.png)
![2](https://user-images.githubusercontent.com/16473366/31890037-66258c3a-b834-11e7-87da-d93c25be42df.png)
![3](https://user-images.githubusercontent.com/16473366/31890038-666ac520-b834-11e7-845a-931f1b9fb1e1.png)

**Comment by amayadream** [comment]
从第三张图片看, 应该是没有重新编译重启项目, IDEA中断点行前面出现这个图标![image](https://user-images.githubusercontent.com/11255896/31921878-4542477c-b8a4-11e7-853f-c302265cef2c.png)一般代表代码修改过但是没有编译重启.

还有你在IMessageService接口的实现类注册了service, 那么在使用的时候应该使用@Resource注入service
```
@Resource
private IMessageService messageService;
```

**Comment by xifumengmengda** [comment]
现在报错这个，反射解析出错。messageService.insert(message1);这一行直接报错。也不进入断点。全部代码如下。直接引用接口是没有问题的吧。
![1](https://user-images.githubusercontent.com/16473366/31923490-60f60c02-b8ad-11e7-84a3-c87ed6540317.png)
![2](https://user-images.githubusercontent.com/16473366/31923491-615f0e28-b8ad-11e7-8259-98c79ba0a9fc.png)
![3](https://user-images.githubusercontent.com/16473366/31923492-6191338a-b8ad-11e7-8344-33a567363ea2.png)
![4](https://user-images.githubusercontent.com/16473366/31923493-61c42812-b8ad-11e7-939c-ba1578c6edf3.png)
![5](https://user-images.githubusercontent.com/16473366/31923494-61f631c2-b8ad-11e7-89a0-9e7e9bcab986.png)
![6](https://user-images.githubusercontent.com/16473366/31923495-62291bf0-b8ad-11e7-9311-2a9bfe4d0d8e.png)
![7](https://user-images.githubusercontent.com/16473366/31923496-625dae7e-b8ad-11e7-9ce1-873683e7f0f7.png)
![8](https://user-images.githubusercontent.com/16473366/31923497-62912f4c-b8ad-11e7-9814-e768ec9c7853.png)

**Comment by amayadream** [comment]
1.主要错误不是反射出错, 而是IMessageService没有注入进来, 所以messageService.insert()就会报空指针异常

2.解决IMessageService的办法是:
把`HttpSessionConfigurator`类的extends改成`SpringConfigurator`
```
public class HttpSessionConfigurator extends SpringConfigurator {

}
```
在`ChatServer`中以构造方法的方式注入IMessageService
```
    private IMessageService messageService;

    @Autowired
    public ChatServer(IMessageService messageService) {
        this.messageService= messageService;
    }
```
这种处理办法的本质还是从spring的上下文中取出指定的bean

3.问题成因:
出现这个问题的原因是因为@ServerEndpoint注册的bean由spring mvc管理, 而你的IMessageService由spring管理, 具体涉及到spring和spring mvc两个容器的知识, 感兴趣可以去了解一下.

**Comment by xifumengmengda** [comment]
的确是的，谢谢你的耐心讲解哈，现在已经可以了。
